# Generated by Django 2.2.14 on 2020-11-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.DateTimeField()),
                ('estudiantes', models.ManyToManyField(related_name='estudiante', to='estudiantes.Estudiante')),
            ],
        ),
    ]
